### ISSUE TITLE
Vue3 Support?

### ISSUE THREAD

**Issue by iriarte300** [awesome-webextension/vue-plugin-webextension-i18n#4]
Hi there! Does the plugin support Vue3? I have tried as follows:

![image](https://user-images.githubusercontent.com/3834513/187736206-058543c1-2f66-44d1-9f42-3bab7d6aaef1.png)

but I get the following runtime error:

![image](https://user-images.githubusercontent.com/3834513/187736687-e4beeb62-659e-47e3-ada8-891d59d787bb.png)

Thank you!

**Comment by crimx** [comment]
Added support for Vue3. Please upgrade the package.

**Comment by iriarte300** [comment]
@crimx you rock! Works great!
